project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Hi, I'm Jiaxin(Jesse)"
  site-url: https://jiaxin-jesse-xue.github.io
  favicon: misc/info/image.png
  repo-url: https://github.com/Jiaxin-Jesse-Xue/Jiaxin-Jesse-Xue.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: "© 2025 Jiaxin(Jesse) Xue"
    right:
      - icon: github
        href: https://github.com/Jiaxin-Jesse-Xue/Jiaxin-Jesse-Xue.github.io


  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Publications"
        href: publications.qmd

      - text: "Conference Papers"
        href: cpaper.qmd

      - text: "Teaching"
        href: teaching.qmd
             
      - text: "Wechat Posts"
        href: post.qmd
             
      - text: "About me"
        href: about_me.qmd
        

format:
  html:
    theme: styles.scss
    toc: true           
    toc-position: right  
    toc-depth: 3


